# Generated by Django 3.2.7 on 2021-09-12 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/import/', verbose_name='file')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='imported at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.departament', verbose_name='department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'import',
                'verbose_name_plural': 'imports',
            },
        ),
    ]
