# Generated by Django 3.2.7 on 2021-09-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_importprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleproperties',
            options={'verbose_name': 'article property', 'verbose_name_plural': 'article properties'},
        ),
    ]
