# Generated by Django 3.2.7 on 2021-09-23 14:43

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_alter_articleproperties_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='upload/departament/', verbose_name='image')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='commercial.departament', verbose_name='image')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
