# Generated by Django 3.2.7 on 2021-09-24 13:11

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_alter_articleproperties_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='upload/start_page/', verbose_name='image')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='order')),
                ('departament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.departament')),
            ],
            options={
                'verbose_name': 'start page image',
                'verbose_name_plural': 'start page images',
            },
        ),
    ]
