# Generated by Django 3.2.7 on 2021-09-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_startpageimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startpageimage',
            options={'ordering': ['order'], 'verbose_name': 'start page image', 'verbose_name_plural': 'start page images'},
        ),
    ]
