# Generated by Django 3.2.7 on 2021-09-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_departamentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='DepartamentImage',
            new_name='StartPageImage',
        ),
        migrations.AlterField(
            model_name='startpageimage',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='commercial.startpage', verbose_name='image'),
        ),
    ]
