# Generated by Django 3.2.7 on 2021-09-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_alter_startpageimage_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='startpageimage',
            index=models.Index(fields=['departament', 'order'], include=('image',), name='department_order'),
        ),
    ]
