# Generated by Django 3.2.7 on 2021-09-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_auto_20210923_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StartPageImage',
        ),
    ]
