# Generated by Django 3.2.8 on 2021-10-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_create_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importprice',
            name='file',
            field=models.FileField(upload_to='upload/import/%Y/%m/%d/', verbose_name='file'),
        ),
    ]
