# Generated by Django 3.2.7 on 2021-09-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_startpageimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startpageimage',
            old_name='department',
            new_name='departament',
        ),
    ]
