# Generated by Django 3.2.8 on 2021-10-26 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0010_strip_categories_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': 'departament', 'verbose_name_plural': 'departaments'},
        ),
        migrations.RemoveConstraint(
            model_name='articleproperties',
            name='unique_article_property',
        ),
        migrations.RemoveConstraint(
            model_name='categoryproperties',
            name='unique_category_property',
        ),
        migrations.RemoveConstraint(
            model_name='departament',
            name='unique_department',
        ),
        migrations.RemoveIndex(
            model_name='startpageimage',
            name='department_order',
        ),
        migrations.RenameField(
            model_name='articleproperties',
            old_name='department',
            new_name='departament',
        ),
        migrations.RenameField(
            model_name='categoryproperties',
            old_name='department',
            new_name='departament',
        ),
        migrations.RenameField(
            model_name='importprice',
            old_name='department',
            new_name='departament',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='department',
            new_name='departament',
        ),
        migrations.AddIndex(
            model_name='startpageimage',
            index=models.Index(fields=['departament', 'order'], include=('image',), name='departament_order'),
        ),
        migrations.AddConstraint(
            model_name='articleproperties',
            constraint=models.UniqueConstraint(fields=('departament', 'article'), name='unique_article_property'),
        ),
        migrations.AddConstraint(
            model_name='categoryproperties',
            constraint=models.UniqueConstraint(fields=('departament', 'category'), name='unique_category_property'),
        ),
        migrations.AddConstraint(
            model_name='departament',
            constraint=models.UniqueConstraint(fields=('country', 'email'), name='unique_departament'),
        ),
    ]
