# Generated by Django 3.2.8 on 2021-11-18 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0011_auto_20211026_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importprice',
            options={'verbose_name': 'import price', 'verbose_name_plural': 'import prices'},
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='is new'),
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='is spacial'),
        ),
        migrations.AlterField(
            model_name='importprice',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.departament', verbose_name='departament'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.departament', verbose_name='departament'),
        ),
        migrations.CreateModel(
            name='ImportSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/import/%Y/%m/%d/', verbose_name='file')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='imported at')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.departament', verbose_name='departament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'import special',
                'verbose_name_plural': 'import specials',
            },
        ),
        migrations.CreateModel(
            name='ImportNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/import/%Y/%m/%d/', verbose_name='file')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='imported at')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.departament', verbose_name='departament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'import new',
                'verbose_name_plural': 'import news',
            },
        ),
    ]
