# Generated by Django 3.2.8 on 2021-11-22 14:43

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0012_auto_20211118_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='photos/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='photos/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='importnew',
            name='file',
            field=models.FileField(upload_to='import_new/%Y/%m/%d/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='importprice',
            name='file',
            field=models.FileField(upload_to='import_price/%Y/%m/%d/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='importspecial',
            name='file',
            field=models.FileField(upload_to='import_special/%Y/%m/%d/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='startpageimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='start_page/', verbose_name='image'),
        ),
    ]
