# Generated by Django 3.2.8 on 2021-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0013_auto_20211122_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleproperties',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='is special'),
        ),
    ]
