# Generated by Django 3.2.8 on 2021-11-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0014_alter_articleproperties_is_special'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startpageimage',
            options={'ordering': ['order'], 'verbose_name': 'start page image', 'verbose_name_plural': 'start page images'},
        ),
        migrations.RemoveIndex(
            model_name='startpageimage',
            name='departament_order',
        ),
        migrations.RemoveField(
            model_name='startpageimage',
            name='departament',
        ),
        migrations.AddIndex(
            model_name='startpageimage',
            index=models.Index(fields=['order'], include=('image',), name='order'),
        ),
    ]
