# Generated by Django 3.2.9 on 2021-11-25 09:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0015_auto_20211122_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('about', 'about'), ('contacts', 'contacts')], null=True, verbose_name='slug')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='text')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.departament', verbose_name='departament')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
        ),
    ]
