# Generated by Django 3.2.9 on 2021-11-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0016_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.departament'),
        ),
    ]
