# Generated by Django 3.2.9 on 2021-11-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0018_auto_20211125_1633'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='startpageimage',
            name='order',
        ),
        migrations.AddField(
            model_name='article',
            name='vendor_code',
            field=models.CharField(max_length=255, null=True, verbose_name='vendor code'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['vendor_code'], name='vendor_code'),
        ),
        migrations.AddIndex(
            model_name='startpageimage',
            index=models.Index(fields=['order'], name='order'),
        ),
    ]
