# Generated by Django 3.2.9 on 2021-11-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0019_auto_20211129_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleproperties',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='barcode'),
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='image_link',
            field=models.URLField(blank=True, null=True, verbose_name='image_link'),
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='length'),
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='retail_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='site_link',
            field=models.URLField(blank=True, null=True, verbose_name='image_link'),
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='image_link'),
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='volume'),
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='articleproperties',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='width'),
        ),
    ]
