# Generated by Django 3.2.9 on 2021-11-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0020_auto_20211129_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleproperties',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='trade price'),
        ),
        migrations.AlterField(
            model_name='articleproperties',
            name='retail_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='retail price'),
        ),
    ]
