# Generated by Django 3.2.9 on 2021-11-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0021_auto_20211129_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleproperties',
            name='image_link',
            field=models.URLField(blank=True, null=True, verbose_name='image link'),
        ),
        migrations.AlterField(
            model_name='articleproperties',
            name='site_link',
            field=models.URLField(blank=True, null=True, verbose_name='site link'),
        ),
        migrations.AlterField(
            model_name='articleproperties',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='video link'),
        ),
    ]
