# Generated by Django 3.2.9 on 2021-12-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0023_profile_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='volume',
            field=models.PositiveIntegerField(default=0, verbose_name='volume'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='weight'),
        ),
    ]
