# Generated by Django 3.2.9 on 2021-12-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0024_auto_20211201_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='barcode'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='company'),
        ),
    ]
