# Generated by Django 3.2.9 on 2021-12-02 20:34

from django.db import migrations


def clear_orders(apps, schema_editor):
    OrderItem = apps.get_model('commercial', 'OrderItem')
    OrderItem.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0026_orderitem_name'),
    ]

    operations = [
        migrations.RunPython(clear_orders, reverse_code=migrations.RunPython.noop)
    ]
