# Generated by Django 3.2.9 on 2021-12-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0030_orderitem_full_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, default=0, verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, default=0, verbose_name='weight'),
        ),
    ]
