# Generated by Django 3.2.10 on 2021-12-21 12:06

import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0032_auto_20211217_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='photos/%Y/%m/%d/%H/%m/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='articleproperties',
            name='main_image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='photos/%Y/%m/%d/%H/%m/', verbose_name='main image'),
        ),
        migrations.AlterField(
            model_name='importnew',
            name='file',
            field=models.FileField(upload_to='import_new/%Y/%m/%d/%H/%m/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='importprice',
            name='file',
            field=models.FileField(upload_to='import_price/%Y/%m/%d/%H/%m/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='importspecial',
            name='file',
            field=models.FileField(upload_to='import_special/%Y/%m/%d/%H/%m/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='startpageimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='start_page/%Y/%m/%d/%H/%m/', verbose_name='image'),
        ),
    ]
