# Generated by Django 3.2.10 on 2021-12-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0035_articleproperties_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleproperties',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='articleproperties',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='articleproperties',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='articleproperties',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='articleproperties',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='width'),
        ),
    ]
