# Generated by Django 3.2.10 on 2021-12-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0036_auto_20211227_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='weight'),
        ),
    ]
