# Generated by Django 3.2.10 on 2021-12-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0037_auto_20211227_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='main_image_url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='main image url'),
        ),
    ]
