# Generated by Django 3.2.12 on 2023-08-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0038_orderitem_main_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='delivery_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='delivery price'),
        ),
    ]
