# Generated by Django 3.2.12 on 2023-09-01 09:50

from django.db import migrations
from django.db.models.functions import Trim


def strip_id_fields(apps, schema_editor):
    Article = apps.get_model('commercial', 'Article')
    ArticleProperties = apps.get_model('commercial', 'ArticleProperties')
    Category = apps.get_model('commercial', 'Category')

    Article.objects.update(id=Trim('id'))
    ArticleProperties.objects.update(article_id=Trim('article_id'))
    Category.objects.update(id=Trim('id'))
    Category.objects.update(parent_id=Trim('parent_id'))

class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0039_departament_delivery_price'),
    ]

    operations = [
        migrations.RunPython(strip_id_fields, reverse_code=migrations.RunPython.noop)
    ]
