# Generated by Django 3.2.12 on 2023-09-01 09:50

from django.db import migrations


def clear_db(apps, schema_editor):
    OrderItem = apps.get_model('commercial', 'OrderItem')
    Article = apps.get_model('commercial', 'Article')
    ArticleProperties = apps.get_model('commercial', 'ArticleProperties')
    Category = apps.get_model('commercial', 'Category')

    OrderItem.objects.all().delete()
    ArticleProperties.objects.all().delete()
    Article.objects.all().delete()
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0039_departament_delivery_price'),
    ]

    operations = [
        migrations.RunPython(clear_db, reverse_code=migrations.RunPython.noop)
    ]
