# Generated by Django 3.2.12 on 2023-10-10 15:05

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0040_clear_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='delivery price')),
            ],
            options={
                'verbose_name': 'delivery price',
                'verbose_name_plural': 'delivery prices',
            },
        ),
        migrations.RemoveField(
            model_name='departament',
            name='delivery_price',
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('country', 'price'), name='unique_delivery_price'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.delivery', verbose_name='delivery'),
        ),
    ]
