# Generated by Django 3.2.22 on 2023-10-14 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0041_auto_20231010_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inn',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='inn'),
        ),
        migrations.CreateModel(
            name='UserDebs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=127, verbose_name='document')),
                ('date_of_sale', models.DateField(verbose_name='date of sale')),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'deb',
                'verbose_name_plural': 'debs',
            },
        ),
        migrations.CreateModel(
            name='ImportDebs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='import_debs/%Y/%m/%d/%H/%m/', verbose_name='file')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='imported at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'import deb',
                'verbose_name_plural': 'import debs',
            },
        ),
    ]
