# Generated by Django 3.2.22 on 2023-10-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0042_auto_20231014_1544'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userdebs',
            constraint=models.UniqueConstraint(fields=('user', 'document'), name='unique_user_document'),
        ),
    ]
