# Generated by Django 3.2.22 on 2023-10-26 15:08

import django.core.validators
import django.db.models.deletion
import sorl.thumbnail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0044_auto_20231024_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField(verbose_name='date of purchase')),
                ('product_name', models.CharField(max_length=255, verbose_name='product name')),
                ('invoice', models.CharField(max_length=127, verbose_name='invoice No')),
                ('description', models.TextField(verbose_name='description')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='', verbose_name='photo')),
                ('video', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='video')),
                ('status', models.IntegerField(choices=[(0, 'opened'), (1, 'closed')], default=0, verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'complaint',
                'verbose_name_plural': 'complaints',
            },
        ),
    ]
