# Generated by Django 3.2.22 on 2023-10-26 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0046_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.complaint', verbose_name='complaint'),
        ),
    ]
