# Generated by Django 3.2.22 on 2023-10-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0047_alter_message_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
    ]
