# Generated by Django 3.2.22 on 2023-10-31 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0048_alter_message_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_date'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='description',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='image',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='video',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_of_purchase',
            field=models.DateField(help_text='Please, fill date in format m/d/Y', verbose_name='date of purchase'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachment/%Y/%m/%d/%H/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'jpg', 'jpeg', 'png'])], verbose_name='file')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.message', verbose_name='message')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
    ]
