# Generated by Django 3.2.22 on 2023-11-01 12:36
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0049_auto_20231031_1000'),
    ]

    operations = [
        TrigramExtension()
    ]
