# Generated by Django 3.2.22 on 2023-11-01 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0050_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachment/%Y/%m/%d/%H/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv', 'jpg', 'jpeg', 'png'])], verbose_name='file'),
        ),
    ]
