# Generated by Django 3.2.22 on 2023-11-01 12:52

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0051_alter_messageattachment_file'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articleproperties',
            constraint=django.contrib.postgres.indexes.GistIndex(fields=['name'], name='gist_trgm_idx', opclasses=['gist_trgm_ops']),
        ),
    ]
