# Generated by Django 3.2.23 on 2023-11-04 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0052_articleproperties_gist_trgm_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='product_name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.article', verbose_name='article'),
        ),
    ]
