# Generated by Django 3.2.23 on 2023-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0055_auto_20231109_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='is read'),
        ),
    ]
