# Generated by Django 3.2.24 on 2024-04-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0057_auto_20240328_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_buyer',
            field=models.BooleanField(default=True, verbose_name='is buyer'),
        ),
    ]
