# Generated by Django 3.2.25 on 2024-04-21 13:39

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0059_alter_orderitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='excluded_categories',
            field=models.ManyToManyField(limit_choices_to=models.Q(('department_id', django.db.models.expressions.F('profile.department_id'))), to='commercial.CategoryProperties', verbose_name='excluded categories'),
        ),
    ]
