# Generated by Django 3.2.25 on 2024-06-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0062_alter_profile_excluded_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='departament',
        ),
    ]
