# Generated by Django 3.2.25 on 2024-06-14 15:23

from django.db import migrations


def fix_pl_article_image(apps, schema_editor):
    ArticleProperties = apps.get_model('commercial', 'ArticleProperties')
    for article in ArticleProperties.objects.all():
        if not str(article.article_id).startswith("PL"):
            continue
        ArticleProperties.objects.filter(article_id=article.article_id[2:]).update(main_image=article.main_image)

class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0063_remove_articleimage_departament'),
    ]

    operations = [
        migrations.RunPython(fix_pl_article_image, reverse_code=migrations.RunPython.noop)
    ]
