# Generated by Django 3.2.25 on 2024-06-14 16:02

from django.db import migrations
from psycopg2.errors import ForeignKeyViolation


def remove_pl_article_from_complaints(apps, schema_editor):
    Complaint = apps.get_model('commercial', 'Complaint')
    for complaint in Complaint.objects.all():
        if not str(complaint.article_id).startswith("PL"):
            continue
        complaint.article_id = complaint.article_id[2:]
        try:
            complaint.save()
        except ForeignKeyViolation:
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0064_fix_pl_articles_images'),
    ]

    operations = [
        migrations.RunPython(remove_pl_article_from_complaints, reverse_code=migrations.RunPython.noop)
    ]
