# Generated by Django 3.2.25 on 2024-06-14 16:07

from django.db import migrations

def remove_pl_article_from_orders(apps, schema_editor):
    OrderItem = apps.get_model('commercial', 'OrderItem')
    Article = apps.get_model('commercial', 'Article')
    for order_item in OrderItem.objects.all():
        if not str(order_item.article_id).startswith("PL"):
            continue
        if Article.objects.filter(id=order_item.article_id[2:]).exists():
            order_item.article_id = order_item.article_id[2:]
            order_item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0065_remove_pl_articles_from_complaints'),
    ]

    operations = [
        migrations.RunPython(remove_pl_article_from_orders, reverse_code=migrations.RunPython.noop)
    ]
