# Generated by Django 3.2.25 on 2025-01-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0066_remove_pl_articles_from_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='currency'),
        ),
    ]
